global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'content_validator'
    static_configs:
      - targets: ['content_validator:8804']

  - job_name: 'rss_manager'
    static_configs:
      - targets: ['rss_manager:8803']

  - job_name: 'user_manager'
    static_configs:
      - targets: ['user_manager:8801']
  
  - job_name: 'writer'
    static_configs:
      - targets: ['writer:8802']


