on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.5.1'  # Specify the Poetry version you wish to use
          virtualenvs-in-project: true  # Creates the virtual environment inside the project directory

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv  # Path to the virtual environment
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run linter
        run: poetry run ruff check .